name: CI

on:
  # Actionsが動くタイミング。masterにプルリクマージされたタイミング
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      ## branch名を取得する君
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
        
      ## バージョンをインクリメントする君, デフォルトはパッチバージョンがインクリメント
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "patch"
          
      ## リリース作成
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.branch-name.outputs.current_branch }}
          body: https://companyname.atlassian.net/browse/${{ steps.branch-name.outputs.current_branch }}
          draft: false
          prerelease: true

